### ISSUE TITLE
Problem getting config information 

### ISSUE THREAD

**Issue by roufsweb** [anonymousx97/social-dl#1]
Dear developer i am trying to run the bot in termux but i am not able to find config information based on you instructions can you please give us some screenshots or something to help 
Please give us broad context on getting config info 
Thank you

**Comment by anonymousx97** [comment]
checked https://github.com/anonymousx97/social-dl#config and sample-config.env?
where exactly are you having issues?

**Comment by roufsweb** [comment]
please give us detailed steps to get the information bellow ,, 
AUTO_DL_MESSAGE_ID
BLOCKED_USERS_MESSAGE_ID 
USERS_MESSAGE_ID
I am a noob pictures will be helpful 
Thank you

**Comment by anonymousx97** [comment]
![Screenshot_20240823-165241_exteraGram](https://github.com/user-attachments/assets/dd6edf00-c5c5-41d6-b0ad-ecebf0a4a501)

send 3 separate messages like this, copy their links and add the number you see at the end of the link as the values for vars.

**Comment by roufsweb** [comment]
``cd social-dl && python3 -m app
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/data/data/com.termux/files/home/test/social-dl/app/__init__.py", line 20, in <module>
    bot: BOT = BOT()
               ^^^^^
  File "/data/data/com.termux/files/home/test/social-dl/app/core/client/client.py", line 41, in __init__
    api_id=int(os.environ.get("API_ID")),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
having this erros when running cd social-dl && python3 -m app

**Comment by anonymousx97** [comment]
did you fill out the vars in config env properly?
check the readme for the steps man
